name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Replace config file
      uses: datamonsters/replace-action
      with:
        files: 'config.yaml'
        replacements: 'DB_USERNAME=root'

    - name: Docker build
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Docker build and push 
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: vskgr/controller:latest
