name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DB_HOST: "mysql"
        envkey_DB_NAME: "ams_back"
        envkey_DB_PORT: 3306
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        envkey_DB_USERNAME: ${{ secrets.DB_USERNAME }}
        directory: /
        file_name: .env
        fail_on_empty: false

    - name: Docker build
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Docker build and push 
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: vskgr/controller:latest
