name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Create .env file
      run: |
        touch env
        echo DB_HOST="mysql" >> env
        echo DB_NAME="ams_back" >> env
        echo DB_PORT="3306" >> env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> env
        echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> env
        echo ARIES_HOST="http://acapy:8031" >> env

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
        
    - name: Docker build and push 
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: vskgr/controller:latest
